spring:
  sql:
    init:
      mode: always
      schema-locations: classpath:org/springframework/batch/core/schema-drop-postgresql.sql
  batch:
    jdbc:
      initialize-schema: always
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: root
    password: password
  jpa:
    show-sql: true        # SQL 실행문을 눈앞에서 처형한다
    properties:
      hibernate:
        format_sql: true    # SQL을 보기 좋게 줄바꿈해서 출력한다
        highlight_sql: true # SQL을 형형색색으로 치장한다

# docker run --name postgres-batch \
#    -e POSTGRES_USER=root \
#    -e POSTGRES_PASSWORD=password \
#    -p 5432:5432 \
#    -d postgres:latest
